export const mockBatches = [
  {
    id: "batch-1",
    name: "Full Stack Development - Batch A",
    description: "React, Node.js, MongoDB",
    totalTrainees: 30,
    trainer: "John Smith",
    behavioralTrainer: "Sarah Johnson",
    mentor: "Michael Brown",
    startDate: "Jan 15, 2024",
    endDate: "Apr 15, 2024",
    status: "active",
    scheduleStatus: {
      onSchedule: 18,
      behind: 8,
      advanced: 4,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 10, 2024" },
      interim: { completed: true, date: "Mar 5, 2024" },
      final: { completed: false, date: "Apr 10, 2024" },
    },
    roomDetails: {
      building: "SDB1",
      floor: 3,
      odcNumber: "ODC-301",
    },
    stakeholders: {
      trainer: { name: "John Smith", hours: 120, hourlyRate: 500 },
      behavioralTrainer: { name: "Sarah Johnson", hours: 80, hourlyRate: 450 },
      mentor: { name: "Michael Brown", hours: 100, hourlyRate: 600 },
    },
    qualifierScores: {
      average: 78,
      highest: 95,
      lowest: 62,
      passRate: 85,
    },
  },
  {
    id: "batch-2",
    name: "Data Science - Batch B",
    description: "Python, ML, Data Analysis",
    totalTrainees: 25,
    trainer: "Emily Davis",
    behavioralTrainer: "Robert Wilson",
    mentor: "Jessica Martinez",
    startDate: "Feb 1, 2024",
    endDate: "May 1, 2024",
    status: "graduated",
    scheduleStatus: {
      onSchedule: 25,
      behind: 0,
      advanced: 0,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 20, 2024" },
      interim: { completed: true, date: "Mar 15, 2024" },
      final: { completed: true, date: "Apr 25, 2024" },
    },
    roomDetails: {
      building: "SDB2",
      floor: 5,
      odcNumber: "ODC-502",
    },
    stakeholders: {
      trainer: { name: "Emily Davis", hours: 150, hourlyRate: 550 },
      behavioralTrainer: { name: "Robert Wilson", hours: 90, hourlyRate: 450 },
      mentor: { name: "Jessica Martinez", hours: 110, hourlyRate: 650 },
    },
    qualifierScores: {
      average: 82,
      highest: 98,
      lowest: 70,
      passRate: 92,
    },
  },
  {
    id: "batch-3",
    name: "Cloud Computing - Batch C",
    description: "AWS, Azure, DevOps",
    totalTrainees: 28,
    trainer: "David Lee",
    behavioralTrainer: "Amanda White",
    mentor: "Chris Anderson",
    startDate: "Jan 20, 2024",
    endDate: "Apr 20, 2024",
    status: "active",
    scheduleStatus: {
      onSchedule: 20,
      behind: 5,
      advanced: 3,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 15, 2024" },
      interim: { completed: false, date: "Mar 20, 2024" },
      final: { completed: false, date: "Apr 15, 2024" },
    },
    roomDetails: {
      building: "SDB3",
      floor: 2,
      odcNumber: "ODC-204",
    },
    stakeholders: {
      trainer: { name: "David Lee", hours: 130, hourlyRate: 520 },
      behavioralTrainer: { name: "Amanda White", hours: 85, hourlyRate: 460 },
      mentor: { name: "Chris Anderson", hours: 105, hourlyRate: 580 },
    },
    qualifierScores: {
      average: 75,
      highest: 92,
      lowest: 58,
      passRate: 80,
    },
  },
];
