export const mockBatches = [
  {
    id: "batch-1",
    name: "Full Stack Development - Batch A",
    description: "React, Node.js, MongoDB",
    totalTrainees: 30,
    trainer: "John Smith",
    behavioralTrainer: "Sarah Johnson",
    mentor: "Michael Brown",
    buddyMentor: "Alex Turner",
    startDate: "Jan 15, 2024",
    endDate: "Apr 15, 2024",
    status: "active",
    currentWeek: 8,
    totalWeeks: 12,
    scheduleStatus: {
      onSchedule: 18,
      behind: 8,
      advanced: 4,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 10, 2024" },
      interim: { completed: true, date: "Mar 5, 2024" },
      final: { completed: false, date: "Apr 10, 2024" },
    },
    roomDetails: {
      building: "SDB1",
      floor: 3,
      odcNumber: "ODC-301",
    },
    stakeholders: {
      trainer: { name: "John Smith", hours: 120 },
      behavioralTrainer: { name: "Sarah Johnson", hours: 80 },
      mentor: { name: "Michael Brown", hours: 100 },
      buddyMentor: { name: "Alex Turner", hours: 60 },
    },
    qualifierScores: {
      average: 78,
      highest: 95,
      lowest: 62,
      passRate: 85,
    },
    trainees: [
      { id: "t1", name: "Rahul Kumar", email: "rahul.k@company.com", employeeId: "EMP001", scheduleAdherence: "On Schedule", learningStatus: "In Progress", interimStatus: "Completed", finalStatus: "Pending", qualifierScore: 85, eligibility: "Eligible" },
      { id: "t2", name: "Priya Sharma", email: "priya.s@company.com", employeeId: "EMP002", scheduleAdherence: "Advanced", learningStatus: "Completed", interimStatus: "Completed", finalStatus: "Pending", qualifierScore: 92, eligibility: "Eligible" },
      { id: "t3", name: "Amit Patel", email: "amit.p@company.com", employeeId: "EMP003", scheduleAdherence: "Behind Schedule", learningStatus: "In Progress", interimStatus: "In Progress", finalStatus: "Pending", qualifierScore: 68, eligibility: "Eligible" },
      { id: "t4", name: "Sneha Reddy", email: "sneha.r@company.com", employeeId: "EMP004", scheduleAdherence: "On Schedule", learningStatus: "In Progress", interimStatus: "Completed", finalStatus: "Pending", qualifierScore: 78, eligibility: "Eligible" },
      { id: "t5", name: "Vikram Singh", email: "vikram.s@company.com", employeeId: "EMP005", scheduleAdherence: "On Schedule", learningStatus: "Completed", interimStatus: "Completed", finalStatus: "Pending", qualifierScore: 88, eligibility: "Eligible" },
    ],
  },
  {
    id: "batch-2",
    name: "Data Science - Batch B",
    description: "Python, ML, Data Analysis",
    totalTrainees: 25,
    trainer: "Emily Davis",
    behavioralTrainer: "Robert Wilson",
    mentor: "Jessica Martinez",
    buddyMentor: "Kevin Lee",
    startDate: "Feb 1, 2024",
    endDate: "May 1, 2024",
    status: "graduated",
    currentWeek: 12,
    totalWeeks: 12,
    scheduleStatus: {
      onSchedule: 25,
      behind: 0,
      advanced: 0,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 20, 2024" },
      interim: { completed: true, date: "Mar 15, 2024" },
      final: { completed: true, date: "Apr 25, 2024" },
    },
    roomDetails: {
      building: "SDB2",
      floor: 5,
      odcNumber: "ODC-502",
    },
    stakeholders: {
      trainer: { name: "Emily Davis", hours: 150 },
      behavioralTrainer: { name: "Robert Wilson", hours: 90 },
      mentor: { name: "Jessica Martinez", hours: 110 },
      buddyMentor: { name: "Kevin Lee", hours: 75 },
    },
    qualifierScores: {
      average: 82,
      highest: 98,
      lowest: 70,
      passRate: 92,
    },
    trainees: [
      { id: "t6", name: "Ananya Gupta", email: "ananya.g@company.com", employeeId: "EMP006", scheduleAdherence: "On Schedule", learningStatus: "Completed", interimStatus: "Completed", finalStatus: "Completed", qualifierScore: 90, eligibility: "Eligible" },
      { id: "t7", name: "Rohan Mehta", email: "rohan.m@company.com", employeeId: "EMP007", scheduleAdherence: "On Schedule", learningStatus: "Completed", interimStatus: "Completed", finalStatus: "Completed", qualifierScore: 85, eligibility: "Eligible" },
    ],
  },
  {
    id: "batch-3",
    name: "Cloud Computing - Batch C",
    description: "AWS, Azure, DevOps",
    totalTrainees: 28,
    trainer: "David Lee",
    behavioralTrainer: "Amanda White",
    mentor: "Chris Anderson",
    buddyMentor: "Sophia Chen",
    startDate: "Jan 20, 2024",
    endDate: "Apr 20, 2024",
    status: "active",
    currentWeek: 6,
    totalWeeks: 12,
    scheduleStatus: {
      onSchedule: 20,
      behind: 5,
      advanced: 3,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 15, 2024" },
      interim: { completed: false, date: "Mar 20, 2024" },
      final: { completed: false, date: "Apr 15, 2024" },
    },
    roomDetails: {
      building: "SDB3",
      floor: 2,
      odcNumber: "ODC-204",
    },
    stakeholders: {
      trainer: { name: "David Lee", hours: 130 },
      behavioralTrainer: { name: "Amanda White", hours: 85 },
      mentor: { name: "Chris Anderson", hours: 105 },
      buddyMentor: { name: "Sophia Chen", hours: 55 },
    },
    qualifierScores: {
      average: 75,
      highest: 92,
      lowest: 58,
      passRate: 80,
    },
    trainees: [
      { id: "t8", name: "Karan Verma", email: "karan.v@company.com", employeeId: "EMP008", scheduleAdherence: "Behind Schedule", learningStatus: "In Progress", interimStatus: "Pending", finalStatus: "Pending", qualifierScore: 72, eligibility: "Eligible" },
      { id: "t9", name: "Divya Nair", email: "divya.n@company.com", employeeId: "EMP009", scheduleAdherence: "Advanced", learningStatus: "In Progress", interimStatus: "Pending", finalStatus: "Pending", qualifierScore: 88, eligibility: "Eligible" },
      { id: "t10", name: "Arjun Rao", email: "arjun.r@company.com", employeeId: "EMP010", scheduleAdherence: "On Schedule", learningStatus: "In Progress", interimStatus: "Pending", finalStatus: "Pending", qualifierScore: 76, eligibility: "Eligible" },
    ],
  },
];
